# Generated by Django 6.0.6 on 2026-07-01 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Име на продукта')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена (лв.)')),
                ('barcode', models.CharField(max_length=50, unique=True, verbose_name='Баркод')),
                ('stock', models.IntegerField(default=0, verbose_name='Наличност')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
